### ISSUE TITLE
FileWizard: ObjectId always zero since last update

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#271]
Hi Andrzej,

since the last update (3.0.13) the object id is always zero in the file wizards.
The function toolsLangServerClient.getNextObjectId returns 0 there.
In 3.0.12 it works fine and the function returns a valid id.

My AL Language version is v7.4.496506

Best regards
David

**Comment by anzwdev** [comment]
Hi David

I was trying to find the problem, but it works for me without any problems. I've released a new version of the extension with a few small changes in the error handling and symbols loading. Could you try if it works now? If it is still broken, could you check if there are any errors logged in the error log by runing "Open AZ AL Dev Tools log file" command?

**Comment by DavidFeldhoff** [comment]
Indeed there is something in the log: The entry is added as I am opening the AL project. 
I tried to reproduce the error in a small project, so that I could send the code to you, but without success. In a small project everythings fine.
```
2021-09-06 07:15:38.199 [ERROR] tid:6 in 'HandleRawMessage' C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\AnZwDev.VSCodeLangServer\Protocol\MessageProtocol\NotificationHandler.cs: line 36
    Error: Object reference not set to an instance of an object.
   at AnZwDev.ALTools.Core.VersionNumber.ParseVersion() in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Core\VersionNumber.cs:line 50
       at AnZwDev.ALTools.Workspace.Serialization.ALProjectMetadataSerializer.ProjectMetadata.CopyInternalsVisibleTo(ALProjectProperties targetProperties) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\Serialization\ALProjectMetadataSerializer.ProjectMetadata.cs:line 124
       at AnZwDev.ALTools.Workspace.Serialization.ALProjectMetadataSerializer.ProjectMetadata.ToALProjectProperties() in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\Serialization\ALProjectMetadataSerializer.ProjectMetadata.cs:line 95
       at AnZwDev.ALTools.Workspace.Serialization.ALProjectMetadataSerializer.LoadFromJson(ALProject project, String jsonContent) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\Serialization\ALProjectMetadataSerializer.cs:line 30
       at AnZwDev.ALTools.Workspace.Serialization.ALProjectMetadataSerializer.LoadFromFile(ALProject project, String path) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\Serialization\ALProjectMetadataSerializer.cs:line 19
       at AnZwDev.ALTools.Workspace.ALProject.Load(Boolean reloadFiles) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\ALProject.cs:line 79
       at AnZwDev.ALTools.Workspace.ALProject.Load() in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\ALProject.cs:line 70
       at AnZwDev.ALTools.Workspace.ALWorkspace.AddProject(String path) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\ALWorkspace.cs:line 64
       at AnZwDev.ALTools.Workspace.ALWorkspace.UpdateProjects(String[] addPaths, String[] removePaths) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\Workspace\ALWorkspace.cs:line 55
       at AnZwDev.ALTools.Server.Handlers.ChangeTracking.WorkspaceFoldersChangeNotificationHandler.HandleNotification(WorkspaceFoldersChangeNotificationRequest parameters, NotificationContext context) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools.Server\Handlers\ChangeTracking\WorkspaceFoldersChangeNotificationHandler.cs:line 21
       at AnZwDev.VSCodeLangServer.Protocol.MessageProtocol.NotificationHandler`1.HandleRawMessage(Message notificationMessage, MessageWriter messageWriter) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\AnZwDev.VSCodeLangServer\Protocol\MessageProtocol\NotificationHandler.cs:line 32
```

**Comment by NKarolak** [comment]
I can confirm that the error still exists. I am getting the very same error log as David. 
BTW, I tested _without_ a workspace.

**Comment by anzwdev** [comment]
Thank you for checking it. I've found a bug, fixed it and released a new version of the extension. I hope that it will work now. 
The problem was caused by the version number parser class that was crashing if version that it was traing to parse was null.

**Comment by DavidFeldhoff** [comment]
I can confirm it works now :) Thanks Andrzej!
