### ISSUE TITLE
Error when running Code Cleanup - remove With

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#346]
Hi, with following settings

```
"alOutline.fixCodeCopMissingParenthesesOnSave": true,
        "alOutline.lockRemovedFieldsCaptions": true,
        "alOutline.addToolTipsToPageFields": true,
        "alOutline.codeCleanupActions": [
            "AddMissingParentheses",
            "AddObjectCaptions",
            "AddTableFieldCaptions",
            "AddToolTips",
            "AddPageFieldCaptions",
            "ConvertObjectIdsToNames",
            "FixIdentifiersCase",
            "FixKeywordsCase",
            "FormatDocument",
            "LockRemovedFieldCaptions",
            "RemoveBeginEnd",
            "RemoveUnusedVariables",
            "RemoveWithStatements",
            "SortPermissions",
            "SortPermissionSetList",
            "SortProperties",
            "SortVariables",
            "TrimTrailingWhitespace"
        ],
        "alOutline.defaultAddPageFieldCaptionsSettings": {
            "setActionGroupsCaptions": true,
            "setActionsCaptions": true,
            "setLabelsCaptions": true,
            "setPartsCaptions": false
        },
        "alOutline.defaultRemoveUnusedVariablesSettings": {
            "removeGlobalVariables": true,
            "removeLocalMethodParameters": true,
            "removeLocalVariables": true
        }

```
I get this error

![image](https://user-images.githubusercontent.com/25268332/158328682-cec00d3d-b289-40f4-b2a3-39603bf0bdb4.png)

Log

```
2022-03-15 08:33:35.349 [ERROR] tid:5 in 'WriteError' C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools.Server\MessageLogWriterImpl.cs: line 30
    Workspace command removeWith error during processing file 'c:\Projects\Dynavision\Dynavision Advanced Pricing\App\src\_AdvPriceWorksheet\cu\PriceWorksheetImplement.codeunit.al': Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.IdentifierNameOrEmptySyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ArgumentListSyntax'.
   at AnZwDev.ALTools.CodeTransformations.WithIdentifiersSyntaxRewriter.VisitIdentifierName(IdentifierNameSyntax node) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\CodeTransformations\WithIdentifiersSyntaxRewriter.cs:line 21
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitIdentifierNameOrEmpty(IdentifierNameOrEmptySyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1157
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 185
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitOptionValues(OptionValuesSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1170
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitOptionDataType(OptionDataTypeSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1886
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitSimpleTypeReference(SimpleTypeReferenceSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1842
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitVariableDeclaration(VariableDeclarationSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1810
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitGlobalVarSection(GlobalVarSectionSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 1797
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitCodeunit(CodeunitSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 200
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitObjectCompilationUnit(ObjectCompilationUnitSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 22
       at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
       at AnZwDev.ALTools.WorkspaceCommands.RemoveWithWorkspaceCommand.ProcessSyntaxNode(SyntaxTree syntaxTree, SyntaxNode node, SemanticModel semanticModel, ALProject project, TextSpan span, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\RemoveWithWorkspaceCommand.cs:line 43
       at AnZwDev.ALTools.WorkspaceCommands.SemanticModelWorkspaceCommand.ProcessSourceCode(SyntaxTree syntaxTree, Compilation compilation, ALProject project, Range range, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\SemanticModelWorkspaceCommand.cs:line 200

```

Can't post the entire file here, but following simplified version gives a similar warning

```
codeunit 50000 "ESCPTest"
{
    Access = Public;

    var
        ErrorMessageHandler: Codeunit "Error Message Handler";
        ErrorMessageManagement: Codeunit "Error Message Management";
        MessageType: Option Error,Warning,Information;
        Customer: record Customer;

    local procedure MyProcedure()
    begin
        ErrorMessageManagement.LogMessage(MessageType::Warning, 0, '', Customer.RecordId, 0, '');
    end;
}
```

**Comment by anzwdev** [comment]
Hi

Thank you for reporting your issue. I was not able to replicate it, but I found a few places that could break if used with different version of Microsoft AL extension/compiler. I've fixed it and released a new version of the extension. Could you check if it works for you now?

**Comment by fvet** [comment]
Hi, just tested again with your latest version, in combination with the AL insider vsix (9.0.x) and issue has been solved. Thx!
