### ISSUE TITLE
Page, Add multiple fields, Cannot select fields

### ISSUE THREAD

**Issue by horstoeko** [anzwdev/al-code-outline#610]
Hi;

First of all, thank you very much for this excellent extension, which I use almost every day.

Now to my problem: Recently, it is no longer possible to use the “Add multiple fields” action (page, etc.).  The fields can no longer be selected. Shortly after selecting a field, the selection tick disappears again immediately.

![image](https://github.com/user-attachments/assets/05b1ee0b-5865-49aa-a5ed-0fdbad2e4713)

I would be delighted if you would look into the matter. 

Many thanks and best regards

**Comment by NKarolak** [comment]
For me on v13.71.0, there even is nothing to select (neither on typing something into the search box):
![image](https://github.com/user-attachments/assets/44e84900-042f-4c26-9a5b-204c07117649)

I suspect using namespaces being the cause for it?

**Comment by horstoeko** [comment]
Hi @anzwdev,
Hi @NKarolak,

today there was an update of VSCode and this extension. Now it seems to work again:

**VSCode**

Version: 1.93.0 (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Datum: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
Betriebssystem: Windows_NT x64 10.0.19045

**AZ AL DevTools**

Name: AZ AL Dev Tools/AL Code Outline
ID: andrzejzwierzchowski.al-code-outline
Beschreibung: AZ AL Development Tools: AL code outline, object browser, object creators
Version: 14.71.1114061
Herausgeber: Andrzej Zwierzchowski
Link zum Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline

**Comment by NKarolak** [comment]
It is not working for me. I was already on VS Code 1.93, but I am not using the pre-release version of the extension.

**Comment by anzwdev** [comment]
There was a problem with fields selection after some changes made to VS Code APIs. I've fixed it in stable version some time ago, but pre-release version was left with old code. I've released a new pre-release version yesterday, which should fix selection problem, but empty list is another issue, which I am going to check as soon as possible.

**Comment by anzwdev** [comment]
Hi @erikrijn

Which version of Microsoft AL extension are you using?

**Comment by anzwdev** [comment]
I've released a new version of the extension with some changes around namespaces and symbols processing yesterday. Could you check if it is still broken in your VS Code?

**Comment by NKarolak** [comment]
> See also #603 For me on v13.71.0 and VS Code 1.93, there even is nothing to select (neither on typing something into the search box): ![image](https://private-user-images.githubusercontent.com/34504100/365644545-44e84900-042f-4c26-9a5b-204c07117649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTIyMTMsIm5iZiI6MTcyNzI1MTkxMywicGF0aCI6Ii8zNDUwNDEwMC8zNjU2NDQ1NDUtNDRlODQ5MDAtMDQyZi00YzI2LTlhNWItMjA0YzA3MTE3NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmZhMDRkOTc0MDQzNDZkNzc2M2U4YmI4YjczNDg3Mzc3NjU4Y2I3Y2MxZjhkZTUwMjg2ODVlYTg3NDU5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.80BuaAyt8bkT7JDvo3RtH8ypd5D9SvOe8ZgciB4gYpg)
> 
> I am using namespaces - could that be the cause?

Unfortunately, my issue is still not fixed in v13.72.0 (on VS Code 1.93.1). I am using namespaces. In repos without namespaces, it works.

**Comment by anzwdev** [comment]
Is there anything in the error log when you run "Open AZ AL Dev Tools log file" command?

**Comment by NKarolak** [comment]
There is one repeating error indeed, however not at the exact moment I try to select table fields:

```
2024-09-26 08:16:19.905 [ERROR] Error: Attempted to read past the end of the stream.
   at StreamJsonRpc.PipeMessageHandler.ReadAtLeastAsync(Int32 requiredBytes, Boolean allowEmpty, CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.DeserializeMessageAsync(Int32 contentLength, Encoding specificEncoding, Encoding defaultEncoding, CancellationToken cancellationToken)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()
   at AnZwDev.ALTools.Server.LanguageServerHost.RunAsync() in D:\a\al-code-outline\al-code-outline\language-server\Shared.AnZwDev.ALTools.Server\LanguageServerHost.cs:line 142
```

**Comment by anzwdev** [comment]
Hi. 

I just want to add some update here. 

The error above is not related to this issue, it is triggered when Visual Studio is closed.

I am still working on a bigger redesign of internal code parsing functionality, which I hope will solve a few problems including this one.

**Comment by NKarolak** [comment]
@anzwdev I've just experimented within my repository. To make "Add multiple fields" work again on a certain page, the only thing I need to change is remove all `using`s. It is even not necessary to replace them with a full qualification (unless you want to compile, of course). Just remove the usings.

**Comment by NKarolak** [comment]
Hm, that's interesting ...
I've found out that the SourceTable is the key to success: When I use a standard table as base table, then "Add multiple fields" works. But when I use one of my own (namespaced) tables, then it is empty.
As soon as I remove the namespace from my base table definition, it works.

**Comment by anzwdev** [comment]
Thank you for these details, I will check it again.
